#!/bin/bash

set -eu

rm $(grep -rl 'Code generated by moq' | grep -v '/update-mocks\.sh$')
for mod in ./ ./awssdkv1 ./awssdkv2
do
  (
    cd ${mod}
    go mod tidy
    go generate ./...
  )
done
git restore $(find . -name 'go.mod') go.sum
rm ./awssdkv1/go.sum ./awssdkv2/go.sum
