name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
        package:
          - ./
          - ./awss3v1/
          - ./awss3v2/
          - ./awss3v2-1.22.2/
          - ./examples/
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Run go test
        run: |
          cd ${{ matrix.package }}
          go vet ./...
          go build ./...

          go test ./... \
            -v \
            -race -coverprofile=cover.out -covermode=atomic
      - name: Tidy check
        run: |
          cd ${{ matrix.package }}
          go mod tidy
          git diff --exit-code go.mod  # must be up-to-date and tidied
      - uses: codecov/codecov-action@v3
        if: matrix.package != './examples/'
        with:
          file: ${{ matrix.package }}cover.out

  mock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Generate mock
        run: |
          find . -name go.mod | while read gomod
          do
            (
              cd $(dirname ${gomod})
              pwd
              go generate ./...
              echo
            )
          done
      - name: Check diff
        run: git diff --exit-code

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'Prepare v')
    needs: [test, mock]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get version
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: echo "${COMMIT_MSG}" | sed -n 's/^Prepare \(v[0-9.]\+\) .*/VERSION=\1/p' | head -n1 > ${GITHUB_ENV}
      - name: create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${VERSION}
          git tag awss3v1/${VERSION}
          git tag awss3v2/${VERSION}
          git tag awss3v2-1.22.2/${VERSION}
          git push origin ${VERSION} awss3v1/${VERSION} awss3v2/${VERSION} awss3v2-1.22.2/${VERSION}
          sleep 1

          gh release create \
            ${VERSION} \
            --draft \
            --title ${VERSION}
