name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.16'
          - '1.17'
        package:
          - ./
          - ./awss3v1/
          - ./awss3v2/
          - ./examples/
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Tidy
        run: |
          cd ${{ matrix.package }}
          go mod tidy
          git diff --exit-code go.mod  # must be up-to-date and tidied
      - name: Run go test
        run: |
          cd ${{ matrix.package }}

          case ${{ matrix.package }} in
            './awss3v1/' | './awss3v2/')
              echo 'replace github.com/at-wat/s3iot => ../' >> go.mod
              ;;
            './examples/')
              echo 'replace github.com/at-wat/s3iot => ../' >> go.mod
              echo 'replace github.com/at-wat/s3iot/awss3v1/ => ../awss3v1/' >> go.mod
              echo 'replace github.com/at-wat/s3iot/awss3v2/ => ../awss3v2/' >> go.mod
              ;;
          esac
          go mod tidy

          go vet ./...
          go build ./...

          go test ./... \
            -v \
            -race -coverprofile=cover.out -covermode=atomic
      - uses: codecov/codecov-action@v2
        if: matrix.package != './examples/'
        with:
          file: ${{ matrix.package }}cover.out
