name: fix
on:
  push:
    branches:
      - renovate/*

jobs:
  go-sum-fix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 2
      - name: fix
        uses: at-wat/go-sum-fix-action@v0
        with:
          git_user: Atsushi Watanabe
          git_email: atsushi.w@ieee.org
          github_token: ${{ secrets.GO_SUM_FIX_GITHUB_TOKEN }}
          commit_style: squash
          push: force
