name: lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Lint
        uses: morphy2k/revive-action@v2
  go-mod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check submodule go.mod
        run: |
          (! grep require awss3v*/go.mod)  # don't add require to awss3v*/go.mod
