name: lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - ./
          - ./awss3v1/
          - ./awss3v2/
          - ./examples/
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Install golint
        run: |
          go get golang.org/x/lint/golint
          go install golang.org/x/lint/golint
          echo $(go env GOPATH)/bin >> ${GITHUB_PATH}
      - name: Lint
        run: |
          cd ${{ matrix.package }}
          golint $(go list ./... | grep -v '\/moq\/') \
            | sed 's/^\([^:]\+\):\([0-9]\+\):\([0-9]\+\): \(.*\)$/::warning file=\1,line=\2,col=\3::\4/'
  go-mod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check paho wrapper go.mod
        run: |
          (! grep require awss3v*/go.mod)  # don't add require to awss3v*/go.mod
