name: lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: morphy2k/revive-action@v2
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check submodule go.mod
        run: |
          (! grep require awssdkv*/go.mod)  # don't add require to awssdkv*/go.mod
