name: moq
on:
  pull_request:
    branches:
      - main

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Update mock
        run: .github/update-mocks.sh
      - name: Check updated
        run: |
          if ! git diff --exit-code
          then
            false
          fi
