name: release-pr
on:
  issues:
    types: [opened, reopened, edited]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Release v')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get version
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: echo "VERSION=${ISSUE_TITLE#Release }" > ${GITHUB_ENV}
      - name: Update go.mod
        run: .github/workflows/bin/update-version.sh ${VERSION}
      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GO_SUM_FIX_GITHUB_TOKEN }}
        run: |
          if git diff --exit-code
          then
            echo "Already updated"
            exit 0
          fi

          git config user.name "at-wat"
          git config user.email "8390204+at-wat@users.noreply.github.com"

          git checkout -b release-${VERSION}
          git add .
          git commit -m "Prepare ${VERSION}"
          git push origin release-${VERSION}
          sleep 1

          gh pr create \
            --base main \
            --head release-${VERSION} \
            --body "Closes #${{ github.event.issue.number }}" \
            --title "Prepare ${VERSION}"
