on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  tag-submodules:
    name: push submodule tags
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: push tags
        run: |
          git tag awssdkv1/$(basename ${TAG})
          git tag awssdkv2/$(basename ${TAG})
          git push origin awssdkv1/$(basename ${TAG}) awssdkv2/$(basename ${TAG})
        env:
          TAG: ${{ github.ref }}
