on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  tag-submodules:
    name: push submodule tags
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: push tags
        run: |
          git tag awss3v1/$(basename ${TAG})
          git tag awss3v2/$(basename ${TAG})
          git push origin awss3v1/$(basename ${TAG}) awss3v2/$(basename ${TAG})
        env:
          TAG: ${{ github.ref }}
